version: '3.7'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    ports:
      - '3306:3306'

  postgresql:
    image: postgres:12-alpine
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'

  node-app:
    build: ./gate-simulator
    image: gate-simulator:1.0
    ports:
      - '9999:9999'